# Generated by Django 2.1.1 on 2018-09-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('description', models.TextField()),
                ('imageurl', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
