# Generated by Django 2.1.1 on 2018-09-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180907_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordertoral',
            new_name='ordertotal',
        ),
    ]
