# Generated by Django 2.1.1 on 2018-09-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180908_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
