# Generated by Django 2.1.1 on 2018-09-08 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180908_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
