# Generated by Django 2.1.1 on 2018-09-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180908_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productid',
            new_name='product',
        ),
    ]
